server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: root
    password: Palku@1332
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

      #eureka:
      # instance:
      #  prefer-ip-address: true
      #client:
      # fetch-registry: true
      #register-with-eureka: true
      #service-url:
    # defaultZone: http://localhost:8761/eureka
  config:
    import: "optional:configserver:http://localhost:8085"
  application:
    name: user-service
management:
  endpoint:
    health:
      show-details: always
